"""Crear modelos Usuario, Comic, Review, Seguimiento, Reporte, Comentario

Revision ID: 9900d106027a
Revises: 
Create Date: 2026-02-17 07:59:22.628450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9900d106027a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comic',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=128), nullable=False),
    sa.Column('autor', sa.String(length=64), nullable=False),
    sa.Column('año', sa.Integer(), nullable=True),
    sa.Column('editorial', sa.String(length=64), nullable=True),
    sa.Column('genero', sa.String(length=32), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('imagen_url', sa.String(length=256), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('promedio_calificacion', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('contraseña_hash', sa.String(length=128), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(), nullable=True),
    sa.Column('es_admin', sa.Boolean(), nullable=True),
    sa.Column('es_moderador', sa.Boolean(), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('avatar_url', sa.String(length=256), nullable=True),
    sa.Column('seguidores_count', sa.Integer(), nullable=True),
    sa.Column('siguiendo_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('reporte',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('contenido_tipo', sa.String(length=32), nullable=False),
    sa.Column('contenido_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.String(length=64), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('estado', sa.String(length=32), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('comic_id', sa.Integer(), nullable=False),
    sa.Column('calificacion', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['comic_id'], ['comic.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('seguimiento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('seguidor_id', sa.Integer(), nullable=False),
    sa.Column('seguido_id', sa.Integer(), nullable=False),
    sa.Column('fecha_seguimiento', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['seguido_id'], ['usuario.id'], ),
    sa.ForeignKeyConstraint(['seguidor_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('comentario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.Text(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(), nullable=True),
    sa.Column('likes', sa.Integer(), nullable=True),
    sa.Column('dislikes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['review_id'], ['review.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentario')
    op.drop_table('seguimiento')
    op.drop_table('review')
    op.drop_table('reporte')
    op.drop_table('usuario')
    op.drop_table('comic')
    # ### end Alembic commands ###
